<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet ekr_test?>
<leo_file>
<leo_header file_format="2" tnodes="0" max_tnode_index="0" clone_windows="0"/>
<globals/>
<preferences/>
<find_panel_settings/>
<vnodes>
<v t="gcross.20100917213812.1249"><vh>@chapters</vh></v>
<v t="gcross.20100917231323.1281"><vh>@thin tagged-list.cabal</vh></v>
<v t="gcross.20100917213812.1278"><vh>@thin Data/List/Tagged.hs</vh></v>
</vnodes>
<tnodes>
<t tx="gcross.20100917213812.1249"></t>
</tnodes>
</leo_file>
